services:
  mira:
    build:
      context: ..
      dockerfile: docker/Dockerfile.dev
    container_name: mira-dev
    env_file:
      - ../.env
    ports:
      - "8040:80"
    volumes:
      - ../src:/app/src:delegated
      - ../scripts:/app/scripts:delegated
      # Conditional SDK volume (will be ignored if path doesn't exist)
      # - /Users/nicolomicheletti/StudioProjects/AugmentOS/augmentos_cloud/packages/sdk:/app/node_modules/@augmentos/sdk:delegated
      # Don't sync other node_modules back to host
      - /app/node_modules
    environment:
      - PORT=80
      - NODE_ENV=development
    command: ["bun", "--hot", "src/index.ts"]
    restart: "no"
    stdin_open: true
    tty: true
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    networks:
      - augmentos-network-dev

networks:
  augmentos-network-dev:
    external: true
    name: augmentos-network-dev